services:
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgre:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PW}
